# Site settings
title: Digital Cuisine blog
description: > # this means to ignore newlines until "baseurl:"
  Digital Cuisine is a place where something is always cooking.
  Here you'll find the latest thoughts from our cooks.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.digitalcuisine.fr" # the base hostname & protocol for your site
twitter_username: digital_cuisine
github_username:  digitalcuisine
facebook_username: DigitalCuisine

# Build settings
markdown: kramdown
